var sankeyData = [
  {
    "name": "ISC-Kasaisa",
    "full_name": "ISC to Kasaisa",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Kasaisa (NGA)",
    "to_site": "Kasaisa",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 23502,
    "female": 28969,
    "under5": 14154,
    "5to17": 16305,
    "under18": 30459,
    "18plus": 22012
  },
  {
    "name": "ISC-Monguno",
    "full_name": "ISC to Monguno",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Monguno (NGA)",
    "to_site": "Monguno",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 246,
    "male": 119,
    "female": 127,
    "under5": 54,
    "5to17": 80,
    "under18": 134,
    "18plus": 112
  },
  {
    "name": "ISC-Biu",
    "full_name": "ISC to Biu",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Biu (NGA)",
    "to_site": "Biu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 12,
    "male": 7,
    "female": 5,
    "under5": 4,
    "5to17": 5,
    "under18": 9,
    "18plus": 3
  },
  {
    "name": "ISC-Gombi",
    "full_name": "ISC to Gombi",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gombi (NGA)",
    "to_site": "Gombi",
    "to_region": "Adamawa",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 9,
    "male": 3,
    "female": 6,
    "under5": 2,
    "5to17": 1,
    "under18": 3,
    "18plus": 6
  },
  {
    "name": "ISC-Minawao",
    "full_name": "ISC to Minawao",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Minawao (CMR)",
    "to_site": "Minawao",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 140,
    "male": 61,
    "female": 79,
    "under5": 32,
    "5to17": 31,
    "under18": 63,
    "18plus": 77
  },
  {
    "name": "ISC-Logone_et_Chari",
    "full_name": "ISC to Logone et Chari",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Logone_et_Chari (CMR)",
    "to_site": "Logone_et_Chari",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 2082,
    "male": 942,
    "female": 1140,
    "under5": 582,
    "5to17": 633,
    "under18": 1215,
    "18plus": 867
  },
  {
    "name": "ISC-Mayo_Sava",
    "full_name": "ISC to Mayo Sava",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Mayo_Sava (CMR)",
    "to_site": "Mayo_Sava",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 116,
    "male": 56,
    "female": 60,
    "under5": 27,
    "5to17": 41,
    "under18": 68,
    "18plus": 48
  },
  {
    "name": "ISC-Diffa",
    "full_name": "ISC to Diffa",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Diffa (NER)",
    "to_site": "Diffa",
    "to_region": "Diffa",
    "to_country": "Niger",
    "to_c_code": "NER",
    "weight": 843,
    "male": 396,
    "female": 447,
    "under5": 220,
    "5to17": 258,
    "under18": 478,
    "18plus": 365
  },
  {
    "name": "ISC-Dar_Es_Salam",
    "full_name": "ISC to Dar Es Salam",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Dar_Es_Salam (CHD)",
    "to_site": "Dar_Es_Salam",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 563,
    "male": 268,
    "female": 295,
    "under5": 161,
    "5to17": 165,
    "under18": 326,
    "18plus": 237
  },
  {
    "name": "ISC-Ngouboua",
    "full_name": "ISC to Ngouboua",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Ngouboua (CHD)",
    "to_site": "Ngouboua",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 281,
    "male": 114,
    "female": 167,
    "under5": 88,
    "5to17": 79,
    "under18": 167,
    "18plus": 114
  },
  {
    "name": "ISC-Gulani",
    "full_name": "ISC to Gulani",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gulani (NGA)",
    "to_site": "Gulani",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 8,
    "male": 5,
    "female": 3,
    "under5": 1,
    "5to17": 2,
    "under18": 3,
    "18plus": 5
  },
  {
    "name": "ISC-Maiduguri",
    "full_name": "ISC to Maiduguri",
    "from": "ISC",
    "from_site": "ISC",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Maiduguri (NGA)",
    "to_site": "Maiduguri",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 379,
    "male": 169,
    "female": 210,
    "under5": 117,
    "5to17": 106,
    "under18": 223,
    "18plus": 156
  },
  {
    "name": "Kasaisa-ISC",
    "full_name": "Kasaisa to ISC",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "ISC (NGA)",
    "to_site": "ISC",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 30,
    "male": 12,
    "female": 18,
    "under5": 8,
    "5to17": 8,
    "under18": 16,
    "18plus": 14
  },
  {
    "name": "Kasaisa-Monguno",
    "full_name": "Kasaisa to Monguno",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Monguno (NGA)",
    "to_site": "Monguno",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 8,
    "male": 4,
    "female": 4,
    "under5": 2,
    "5to17": 3,
    "under18": 5,
    "18plus": 3
  },
  {
    "name": "Kasaisa-Biu",
    "full_name": "Kasaisa to Biu",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Biu (NGA)",
    "to_site": "Biu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 0,
    "female": 1,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 1
  },
  {
    "name": "Kasaisa-Gombi",
    "full_name": "Kasaisa to Gombi",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gombi (NGA)",
    "to_site": "Gombi",
    "to_region": "Adamawa",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 1,
    "male": 0,
    "female": 1,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 1
  },
  {
    "name": "Kasaisa-Minawao",
    "full_name": "Kasaisa to Minawao",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Minawao (CMR)",
    "to_site": "Minawao",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 14,
    "male": 5,
    "female": 9,
    "under5": 2,
    "5to17": 1,
    "under18": 3,
    "18plus": 11
  },
  {
    "name": "Kasaisa-Logone_et_Chari",
    "full_name": "Kasaisa to Logone et Chari",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Logone_et_Chari (CMR)",
    "to_site": "Logone_et_Chari",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 39,
    "male": 13,
    "female": 26,
    "under5": 5,
    "5to17": 8,
    "under18": 13,
    "18plus": 26
  },
  {
    "name": "Kasaisa-Mayo_Sava",
    "full_name": "Kasaisa to Mayo Sava",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Mayo_Sava (CMR)",
    "to_site": "Mayo_Sava",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 6,
    "male": 2,
    "female": 4,
    "under5": 1,
    "5to17": 0,
    "under18": 1,
    "18plus": 5
  },
  {
    "name": "Kasaisa-Diffa",
    "full_name": "Kasaisa to Diffa",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Diffa (NER)",
    "to_site": "Diffa",
    "to_region": "Diffa",
    "to_country": "Niger",
    "to_c_code": "NER",
    "weight": 35,
    "male": 13,
    "female": 22,
    "under5": 8,
    "5to17": 10,
    "under18": 18,
    "18plus": 17
  },
  {
    "name": "Kasaisa-Dar_Es_Salam",
    "full_name": "Kasaisa to Dar Es Salam",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Dar_Es_Salam (CHD)",
    "to_site": "Dar_Es_Salam",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 23,
    "male": 11,
    "female": 12,
    "under5": 4,
    "5to17": 9,
    "under18": 13,
    "18plus": 10
  },
  {
    "name": "Kasaisa-Ngouboua",
    "full_name": "Kasaisa to Ngouboua",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Ngouboua (CHD)",
    "to_site": "Ngouboua",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 10,
    "male": 5,
    "female": 5,
    "under5": 5,
    "5to17": 3,
    "under18": 8,
    "18plus": 2
  },
  {
    "name": "Kasaisa-Gulani",
    "full_name": "Kasaisa to Gulani",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gulani (NGA)",
    "to_site": "Gulani",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 1,
    "female": 0,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 1
  },
  {
    "name": "Kasaisa-Maiduguri",
    "full_name": "Kasaisa to Maiduguri",
    "from": "Kasaisa",
    "from_site": "Kasaisa",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Maiduguri (NGA)",
    "to_site": "Maiduguri",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 13,
    "male": 4,
    "female": 9,
    "under5": 4,
    "5to17": 4,
    "under18": 8,
    "18plus": 5
  },
  {
    "name": "Monguno-ISC",
    "full_name": "Monguno to ISC",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "ISC (NGA)",
    "to_site": "ISC",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 60,
    "male": 27,
    "female": 33,
    "under5": 12,
    "5to17": 16,
    "under18": 28,
    "18plus": 32
  },
  {
    "name": "Monguno-Kasaisa",
    "full_name": "Monguno to Kasaisa",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Kasaisa (NGA)",
    "to_site": "Kasaisa",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 3,
    "male": 2,
    "female": 1,
    "under5": 0,
    "5to17": 3,
    "under18": 3,
    "18plus": 0
  },
  {
    "name": "Monguno-Biu",
    "full_name": "Monguno to Biu",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Biu (NGA)",
    "to_site": "Biu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 5,
    "male": 4,
    "female": 1,
    "under5": 0,
    "5to17": 3,
    "under18": 3,
    "18plus": 2
  },
  {
    "name": "Monguno-Gombi",
    "full_name": "Monguno to Gombi",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gombi (NGA)",
    "to_site": "Gombi",
    "to_region": "Adamawa",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 7,
    "male": 4,
    "female": 3,
    "under5": 2,
    "5to17": 3,
    "under18": 5,
    "18plus": 2
  },
  {
    "name": "Monguno-Minawao",
    "full_name": "Monguno to Minawao",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Minawao (CMR)",
    "to_site": "Minawao",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 80,
    "male": 44,
    "female": 36,
    "under5": 18,
    "5to17": 22,
    "under18": 40,
    "18plus": 40
  },
  {
    "name": "Monguno-Logone_et_Chari",
    "full_name": "Monguno to Logone et Chari",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Logone_et_Chari (CMR)",
    "to_site": "Logone_et_Chari",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 538,
    "male": 244,
    "female": 294,
    "under5": 137,
    "5to17": 188,
    "under18": 325,
    "18plus": 213
  },
  {
    "name": "Monguno-Mayo_Sava",
    "full_name": "Monguno to Mayo Sava",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Mayo_Sava (CMR)",
    "to_site": "Mayo_Sava",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 60,
    "male": 22,
    "female": 38,
    "under5": 12,
    "5to17": 24,
    "under18": 36,
    "18plus": 24
  },
  {
    "name": "Monguno-Diffa",
    "full_name": "Monguno to Diffa",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Diffa (NER)",
    "to_site": "Diffa",
    "to_region": "Diffa",
    "to_country": "Niger",
    "to_c_code": "NER",
    "weight": 564,
    "male": 245,
    "female": 319,
    "under5": 136,
    "5to17": 192,
    "under18": 328,
    "18plus": 236
  },
  {
    "name": "Monguno-Dar_Es_Salam",
    "full_name": "Monguno to Dar Es Salam",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Dar_Es_Salam (CHD)",
    "to_site": "Dar_Es_Salam",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 359,
    "male": 164,
    "female": 195,
    "under5": 79,
    "5to17": 126,
    "under18": 205,
    "18plus": 154
  },
  {
    "name": "Monguno-Ngouboua",
    "full_name": "Monguno to Ngouboua",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Ngouboua (CHD)",
    "to_site": "Ngouboua",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 417,
    "male": 191,
    "female": 226,
    "under5": 88,
    "5to17": 138,
    "under18": 226,
    "18plus": 191
  },
  {
    "name": "Monguno-Gulani",
    "full_name": "Monguno to Gulani",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gulani (NGA)",
    "to_site": "Gulani",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 4,
    "male": 2,
    "female": 2,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 4
  },
  {
    "name": "Monguno-Maiduguri",
    "full_name": "Monguno to Maiduguri",
    "from": "Monguno",
    "from_site": "Monguno",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Maiduguri (NGA)",
    "to_site": "Maiduguri",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 238,
    "male": 106,
    "female": 132,
    "under5": 67,
    "5to17": 74,
    "under18": 141,
    "18plus": 97
  },
  {
    "name": "Biu-ISC",
    "full_name": "Biu to ISC",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "ISC (NGA)",
    "to_site": "ISC",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 16,
    "male": 10,
    "female": 6,
    "under5": 1,
    "5to17": 9,
    "under18": 10,
    "18plus": 6
  },
  {
    "name": "Biu-Kasaisa",
    "full_name": "Biu to Kasaisa",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Kasaisa (NGA)",
    "to_site": "Kasaisa",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 3,
    "male": 3,
    "female": 0,
    "under5": 1,
    "5to17": 0,
    "under18": 1,
    "18plus": 2
  },
  {
    "name": "Biu-Monguno",
    "full_name": "Biu to Monguno",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Monguno (NGA)",
    "to_site": "Monguno",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 3,
    "male": 1,
    "female": 2,
    "under5": 1,
    "5to17": 0,
    "under18": 1,
    "18plus": 2
  },
  {
    "name": "Biu-Gombi",
    "full_name": "Biu to Gombi",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gombi (NGA)",
    "to_site": "Gombi",
    "to_region": "Adamawa",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 1,
    "male": 1,
    "female": 0,
    "under5": 0,
    "5to17": 1,
    "under18": 1,
    "18plus": 0
  },
  {
    "name": "Biu-Minawao",
    "full_name": "Biu to Minawao",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Minawao (CMR)",
    "to_site": "Minawao",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 12,
    "male": 5,
    "female": 7,
    "under5": 1,
    "5to17": 4,
    "under18": 5,
    "18plus": 7
  },
  {
    "name": "Biu-Logone_et_Chari",
    "full_name": "Biu to Logone et Chari",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Logone_et_Chari (CMR)",
    "to_site": "Logone_et_Chari",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 19,
    "male": 9,
    "female": 10,
    "under5": 3,
    "5to17": 6,
    "under18": 9,
    "18plus": 10
  },
  {
    "name": "Biu-Mayo_Sava",
    "full_name": "Biu to Mayo Sava",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Mayo_Sava (CMR)",
    "to_site": "Mayo_Sava",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 8,
    "male": 1,
    "female": 7,
    "under5": 0,
    "5to17": 1,
    "under18": 1,
    "18plus": 7
  },
  {
    "name": "Biu-Diffa",
    "full_name": "Biu to Diffa",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Diffa (NER)",
    "to_site": "Diffa",
    "to_region": "Diffa",
    "to_country": "Niger",
    "to_c_code": "NER",
    "weight": 18,
    "male": 8,
    "female": 10,
    "under5": 4,
    "5to17": 4,
    "under18": 8,
    "18plus": 10
  },
  {
    "name": "Biu-Dar_Es_Salam",
    "full_name": "Biu to Dar Es Salam",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Dar_Es_Salam (CHD)",
    "to_site": "Dar_Es_Salam",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 12,
    "male": 4,
    "female": 8,
    "under5": 3,
    "5to17": 2,
    "under18": 5,
    "18plus": 7
  },
  {
    "name": "Biu-Ngouboua",
    "full_name": "Biu to Ngouboua",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Ngouboua (CHD)",
    "to_site": "Ngouboua",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 2,
    "male": 1,
    "female": 1,
    "under5": 1,
    "5to17": 0,
    "under18": 1,
    "18plus": 1
  },
  {
    "name": "Biu-Gulani",
    "full_name": "Biu to Gulani",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gulani (NGA)",
    "to_site": "Gulani",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 0,
    "female": 1,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 1
  },
  {
    "name": "Biu-Maiduguri",
    "full_name": "Biu to Maiduguri",
    "from": "Biu",
    "from_site": "Biu",
    "from_region": "Borno",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Maiduguri (NGA)",
    "to_site": "Maiduguri",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 4,
    "male": 2,
    "female": 2,
    "under5": 1,
    "5to17": 0,
    "under18": 1,
    "18plus": 3
  },
  {
    "name": "Gombi-ISC",
    "full_name": "Gombi to ISC",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "ISC (NGA)",
    "to_site": "ISC",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 5,
    "male": 2,
    "female": 3,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 5
  },
  {
    "name": "Gombi-Kasaisa",
    "full_name": "Gombi to Kasaisa",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Kasaisa (NGA)",
    "to_site": "Kasaisa",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 2,
    "female": 3,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 5
  },
  {
    "name": "Gombi-Monguno",
    "full_name": "Gombi to Monguno",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Monguno (NGA)",
    "to_site": "Monguno",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 1,
    "male": 0,
    "female": 1,
    "under5": 0,
    "5to17": 0,
    "under18": 0,
    "18plus": 1
  },
  {
    "name": "Gombi-Biu",
    "full_name": "Gombi to Biu",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Biu (NGA)",
    "to_site": "Biu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 1,
    "female": 0,
    "under5": 0,
    "5to17": 1,
    "under18": 1,
    "18plus": 0
  },
  {
    "name": "Gombi-Minawao",
    "full_name": "Gombi to Minawao",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Minawao (CMR)",
    "to_site": "Minawao",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 16,
    "male": 9,
    "female": 7,
    "under5": 1,
    "5to17": 5,
    "under18": 6,
    "18plus": 10
  },
  {
    "name": "Gombi-Logone_et_Chari",
    "full_name": "Gombi to Logone et Chari",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Logone_et_Chari (CMR)",
    "to_site": "Logone_et_Chari",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 6,
    "male": 4,
    "female": 2,
    "under5": 2,
    "5to17": 1,
    "under18": 3,
    "18plus": 3
  },
  {
    "name": "Gombi-Mayo_Sava",
    "full_name": "Gombi to Mayo Sava",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Mayo_Sava (CMR)",
    "to_site": "Mayo_Sava",
    "to_region": "Far North",
    "to_country": "Cameroon",
    "to_c_code": "CMR",
    "weight": 5,
    "male": 3,
    "female": 2,
    "under5": 0,
    "5to17": 4,
    "under18": 4,
    "18plus": 1
  },
  {
    "name": "Gombi-Diffa",
    "full_name": "Gombi to Diffa",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Diffa (NER)",
    "to_site": "Diffa",
    "to_region": "Diffa",
    "to_country": "Niger",
    "to_c_code": "NER",
    "weight": 12,
    "male": 7,
    "female": 5,
    "under5": 3,
    "5to17": 1,
    "under18": 4,
    "18plus": 8
  },
  {
    "name": "Gombi-Dar_Es_Salam",
    "full_name": "Gombi to Dar Es Salam",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Dar_Es_Salam (CHD)",
    "to_site": "Dar_Es_Salam",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 8,
    "male": 3,
    "female": 5,
    "under5": 2,
    "5to17": 1,
    "under18": 3,
    "18plus": 5
  },
  {
    "name": "Gombi-Ngouboua",
    "full_name": "Gombi to Ngouboua",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Ngouboua (CHD)",
    "to_site": "Ngouboua",
    "to_region": "Lac",
    "to_country": "Chad",
    "to_c_code": "CHD",
    "weight": 2,
    "male": 1,
    "female": 1,
    "under5": 0,
    "5to17": 1,
    "under18": 1,
    "18plus": 1
  },
  {
    "name": "Gombi-Gulani",
    "full_name": "Gombi to Gulani",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Gulani (NGA)",
    "to_site": "Gulani",
    "to_region": "Yobe",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 1,
    "female": 0,
    "under5": 1,
    "5to17": 0,
    "under18": 1,
    "18plus": 0
  },
  {
    "name": "Gombi-Maiduguri",
    "full_name": "Gombi to Maiduguri",
    "from": "Gombi",
    "from_site": "Gombi",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to": "Maiduguri (NGA)",
    "to_site": "Maiduguri",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "weight": 0,
    "male": 1,
    "female": 0,
    "under5": 0,
    "5to17": 1,
    "under18": 1,
    "18plus": 0
  }
]