var sankeyData =[
  {
    "name": "Karim Lamido-Karim Lamido",
    "full_name": "Karim Lamido to Karim Lamido",
    "from": "Karim Lamido",
    "from_site": "Karim Lamido",
    "from_region": "Taraba",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Karim Lamido",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Karim Lamido (NGA)",
    "weight": 7,
    "male": 4,
    "female": 3,
    "under5": 2,
    "5to17": 1,
    "under18": 3,
    "18plus": 4
  },
  {
    "name": "Karim Lamido-Lafia",
    "full_name": "Karim Lamido to Lafia",
    "from": "Karim Lamido",
    "from_site": "Karim Lamido",
    "from_region": "Taraba",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Lafia",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Lafia (NGA)",
    "weight": 37,
    "male": 18,
    "female": 19,
    "under5": 8,
    "5to17": 10,
    "under18": 18,
    "18plus": 19
  },
  {
    "name": "Girei-Lafia",
    "full_name": "Girei to Lafia",
    "from": "Girei",
    "from_site": "Girei",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Lafia",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Lafia (NGA)",
    "weight": 6,
    "male": 3,
    "female": 3,
    "under5": 3,
    "5to17": 2,
    "under18": 5,
    "18plus": 1
  },
  {
    "name": "Buni Yadi-Gulani",
    "full_name": "Buni Yadi to Gulani",
    "from": "Buni Yadi",
    "from_site": "Buni Yadi",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Gulani",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Gulani (NGA)",
    "weight": 6,
    "male": 3,
    "female": 3,
    "under5": 2,
    "5to17": 2,
    "under18": 4,
    "18plus": 2
  },
  {
    "name": "Gujba-Maiduguri",
    "full_name": "Gujba to Maiduguri",
    "from": "Gujba",
    "from_site": "Gujba",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Maiduguri",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Maiduguri (NGA)",
    "weight": 7,
    "male": 5,
    "female": 2,
    "under5": 0,
    "5to17": 6,
    "under18": 6,
    "18plus": 1
  },
  {
    "name": "Buni Yadi-Gujba",
    "full_name": "Buni Yadi to Gujba",
    "from": "Buni Yadi",
    "from_site": "Buni Yadi",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Gujba",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Gujba (NGA)",
    "weight": 14,
    "male": 4,
    "female": 10,
    "under5": 1,
    "5to17": 4,
    "under18": 5,
    "18plus": 9
  },
  {
    "name": "Gujba-Gujba",
    "full_name": "Gujba to Gujba",
    "from": "Gujba",
    "from_site": "Gujba",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Gujba",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Gujba (NGA)",
    "weight": 17,
    "male": 6,
    "female": 11,
    "under5": 7,
    "5to17": 4,
    "under18": 11,
    "18plus": 6
  },
  {
    "name": "Buni Yadi-Damboa",
    "full_name": "Buni Yadi to Damboa",
    "from": "Buni Yadi",
    "from_site": "Buni Yadi",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Damboa",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Damboa (NGA)",
    "weight": 18,
    "male": 14,
    "female": 4,
    "under5": 0,
    "5to17": 8,
    "under18": 8,
    "18plus": 10
  },
  {
    "name": "Gujba-Damboa",
    "full_name": "Gujba to Damboa",
    "from": "Gujba",
    "from_site": "Gujba",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Damboa",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Damboa (NGA)",
    "weight": 17,
    "male": 10,
    "female": 7,
    "under5": 1,
    "5to17": 12,
    "under18": 13,
    "18plus": 4
  },
  {
    "name": "Buni Yadi-Biu",
    "full_name": "Buni Yadi to Biu",
    "from": "Buni Yadi",
    "from_site": "Buni Yadi",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Biu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Biu (NGA)",
    "weight": 26,
    "male": 8,
    "female": 18,
    "under5": 3,
    "5to17": 8,
    "under18": 11,
    "18plus": 15
  },
  {
    "name": "Gujba-Biu",
    "full_name": "Gujba to Biu",
    "from": "Gujba",
    "from_site": "Gujba",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Biu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Biu (NGA)",
    "weight": 9,
    "male": 5,
    "female": 4,
    "under5": 2,
    "5to17": 1,
    "under18": 3,
    "18plus": 6
  },
  {
    "name": "Karim Lamido-Guyuk",
    "full_name": "Karim Lamido to Guyuk",
    "from": "Karim Lamido",
    "from_site": "Karim Lamido",
    "from_region": "Taraba",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Guyuk",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Guyuk (NGA)",
    "weight": 11,
    "male": 8,
    "female": 3,
    "under5": 3,
    "5to17": 5,
    "under18": 8,
    "18plus": 3
  },
  {
    "name": "Buni Yadi-Damaturu",
    "full_name": "Buni Yadi to Damaturu",
    "from": "Buni Yadi",
    "from_site": "Buni Yadi",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Damaturu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Damaturu (NGA)",
    "weight": 19,
    "male": 8,
    "female": 11,
    "under5": 3,
    "5to17": 9,
    "under18": 12,
    "18plus": 7
  },
  {
    "name": "Gujba-Damaturu",
    "full_name": "Gujba to Damaturu",
    "from": "Gujba",
    "from_site": "Gujba",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Damaturu",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Damaturu (NGA)",
    "weight": 20,
    "male": 10,
    "female": 10,
    "under5": 4,
    "5to17": 8,
    "under18": 12,
    "18plus": 8
  },
  {
    "name": "Karim Lamido-Numan",
    "full_name": "Karim Lamido to Numan",
    "from": "Karim Lamido",
    "from_site": "Karim Lamido",
    "from_region": "Taraba",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Numan",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Numan (NGA)",
    "weight": 8,
    "male": 5,
    "female": 3,
    "under5": 2,
    "5to17": 3,
    "under18": 5,
    "18plus": 3
  },
  {
    "name": "Girei-Numan",
    "full_name": "Girei to Numan",
    "from": "Girei",
    "from_site": "Girei",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Numan",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Numan (NGA)",
    "weight": 8,
    "male": 4,
    "female": 4,
    "under5": 2,
    "5to17": 2,
    "under18": 4,
    "18plus": 4
  },
  {
    "name": "Girei-Girei",
    "full_name": "Girei to Girei",
    "from": "Girei",
    "from_site": "Girei",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Girei",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Girei (NGA)",
    "weight": 7,
    "male": 5,
    "female": 2,
    "under5": 2,
    "5to17": 2,
    "under18": 4,
    "18plus": 3
  },
  {
    "name": "Girei-Song",
    "full_name": "Girei to Song",
    "from": "Girei",
    "from_site": "Girei",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Song",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Song (NGA)",
    "weight": 12,
    "male": 10,
    "female": 2,
    "under5": 1,
    "5to17": 3,
    "under18": 4,
    "18plus": 8
  },
  {
    "name": "Girei-Yola",
    "full_name": "Girei to Yola",
    "from": "Girei",
    "from_site": "Girei",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Yola",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Yola (NGA)",
    "weight": 50,
    "male": 19,
    "female": 31,
    "under5": 9,
    "5to17": 19,
    "under18": 28,
    "18plus": 22
  },
  {
    "name": "Buni Yadi-Askira",
    "full_name": "Buni Yadi to Askira",
    "from": "Buni Yadi",
    "from_site": "Buni Yadi",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Askira",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Askira (NGA)",
    "weight": 7,
    "male": 3,
    "female": 4,
    "under5": 1,
    "5to17": 1,
    "under18": 2,
    "18plus": 5
  },
  {
    "name": "Girei-Fufore",
    "full_name": "Girei to Fufore",
    "from": "Girei",
    "from_site": "Girei",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Fufore",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Fufore (NGA)",
    "weight": 9,
    "male": 5,
    "female": 4,
    "under5": 1,
    "5to17": 5,
    "under18": 6,
    "18plus": 3
  },
  {
    "name": "Gujba-Damagum",
    "full_name": "Gujba to Damagum",
    "from": "Gujba",
    "from_site": "Gujba",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Damagum",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Damagum (NGA)",
    "weight": 9,
    "male": 6,
    "female": 3,
    "under5": 1,
    "5to17": 3,
    "under18": 4,
    "18plus": 5
  },
  {
    "name": "Girei-Gombi",
    "full_name": "Girei to Gombi",
    "from": "Girei",
    "from_site": "Girei",
    "from_region": "Adamawa",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Gombi",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Gombi (NGA)",
    "weight": 8,
    "male": 3,
    "female": 5,
    "under5": 1,
    "5to17": 4,
    "under18": 5,
    "18plus": 3
  },
  {
    "name": "Buni Yadi-Benisheikh",
    "full_name": "Buni Yadi to Benisheikh",
    "from": "Buni Yadi",
    "from_site": "Buni Yadi",
    "from_region": "Yobe",
    "from_country": "Nigeria",
    "from_c_code": "NGA",
    "to_site": "Benisheikh",
    "to_region": "Borno",
    "to_country": "Nigeria",
    "to_c_code": "NGA",
    "to": "Benisheikh (NGA)",
    "weight": 6,
    "male": 3,
    "female": 3,
    "under5": 0,
    "5to17": 3,
    "under18": 3,
    "18plus": 3
  }
]
